#pragma once
#include "Vector.h"

enum audiolib_result
{
    AUDIOLIB_FILE_LOAD_STATUS_UNLOADED = 0x66,
    AUDIOLIB_FILE_LOAD_STATUS_LOADED = 0x65,
    AUDIOLIB_FILE_LOAD_STATUS_LOADING = 0x64,
    AUDIOLIB_CUE_WAITING_FOR_BANDWIDTH = 0xB,
    AUDIOLIB_CUE_WAITING_FOR_A_CHANNEL = 0xA,
    AUDIOLIB_ERR_NONE = 0x0,
    AUDIOLIB_ERR_NOT_INITED = 0xFFFFFFFF,
    AUDIOLIB_ERR_MEM_ALLOC_FAILED = 0xFFFFFFFE,
    AUDIOLIB_ERR_FILE_OPEN = 0xFFFFFFFD,
    AUDIOLIB_ERR_FILE_READ = 0xFFFFFFFC,
    AUDIOLIB_ERR_FILE_FORMAT = 0xFFFFFFFB,
    AUDIOLIB_ERR_DSP_INIT_FAILED = 0xFFFFFFFA,
    AUDIOLIB_ERR_THREAD_FAILED = 0xFFFFFFF9,
    AUDIOLIB_ERR_THREAD_PRIORITY_FAILED = 0xFFFFFFF8,
    AUDIOLIB_ERR_THREAD_NOT_CLOSED = 0xFFFFFFF7,
    AUDIOLIB_ERR_NO_PROCESS_SLOTS = 0xFFFFFFF6,
    AUDIOLIB_ERR_NO_SOUNDBANK_SLOTS = 0xFFFFFFF5,
    AUDIOLIB_ERR_NO_PLAY_SLOTS = 0xFFFFFFF4,
    AUDIOLIB_ERR_NO_MORE_MUSIC_SLOTS = 0xFFFFFFF3,
    AUDIOLIB_ERR_NO_MORE_ALR_SLOTS = 0xFFFFFFF2,
    AUDIOLIB_ERR_NO_FOLEY_SLOTS = 0xFFFFFFF1,
    AUDIOLIB_ERR_NOT_PLAYING = 0xFFFFFFF0,
    AUDIOLIB_ERR_NOT_SUPPORTED = 0xFFFFFFEF,
    AUDIOLIB_ERR_SOUNDS_PAUSED = 0xFFFFFFEE,
    AUDIOLIB_ERR_NO_MORE_ENTRIES = 0xFFFFFFED,
    AUDIOLIB_NOT_ENABLED = 0xFFFFFFCE,
    AUDIOLIB_FILE_LOAD_STATUS_ERROR = 0xFFFFFFBB,
    AUDIOLIB_ERR_BAD_INTERNAL = 0xFFFFFF9D,
    AUDIOLIB_ERR_BAD_PARAM = 0xFFFFFF9C,
    AUDIOLIB_ERR_NO_MEMPOOL = 0xFFFFFF9B,
    AUDIOLIB_ERR_BAD_CUE_ID = 0xFFFFFF9A,
    AUDIOLIB_ERR_BAD_BANK_ID = 0xFFFFFF99,
    AUDIOLIB_ERR_BAD_PLAY_ID = 0xFFFFFF98,
    AUDIOLIB_ERR_NO_MARKERS = 0xFFFFFF97,
    AUDIOLIB_ERR_BAD_CATEGORY_ID = 0xFFFFFF96,
    AUDIOLIB_ERR_BAD_MUSIC_ID = 0xFFFFFF95,
    AUDIOLIB_ERR_SOUNDBANK_IN_USE = 0xFFFFFF94,
    AUDIOLIB_ERR_CUE_NOT_FOUND = 0xFFFFFF93,
    AUDIOLIB_ERR_MARKERS_NOT_FOUND = 0xFFFFFF92,
    AUDIOLIB_ERR_NO_MARKER_SLOTS = 0xFFFFFF91,
    AUDIOLIB_ERR_FOLEY_TABLE = 0xFFFFFF90,
    AUDIOLIB_ERR_DIST_TOO_FAR = 0xFFFFFF8F,
    AUDIOLIB_ERR_DONT_PLAY_PERCENTAGE = 0xFFFFFF8E,
    AUDIOLIB_ERR_EXCEED_FOLEY_LIMIT = 0xFFFFFF8D,
    AUDIOLIB_ERR_EXCEED_CATEGORY_LIMIT = 0xFFFFFF8C,
    AUDIOLIB_ERR_MUSIC_TRANSITION_FAILED = 0xFFFFFF8B,
    AUDIOLIB_ERR_CATEGORY_VOLUME_TOO_LOW = 0xFFFFFF8A,
    AUDIOLIB_ERR_VARIATION_NOT_KNOWN = 0xFFFFFF89,
    AUDIOLIB_ERR_MULTI_CUE_NO_SLOTS = 0xFFFFFF88,
    AUDIOLIB_ERR_MULTI_CUE_NO_ROOM = 0xFFFFFF87,
    AUDIOLIB_ERR_CANT_PLAY_WHEN_LOADING = 0xFFFFFF86,
    AUDIOLIB_ERR_NOT_2D = 0xFFFFFF38,
    AUDIOLIB_ERR_NOT_3D = 0xFFFFFF37,
    AUDIOLIB_ERR_NO_MULT_EMITTERS = 0xFFFFFF36,
    AUDIOLIB_ERR_NO_MULT_POSITION = 0xFFFFFF35,
    AUDIOLIB_ERR_HW_INIT_FAILED = 0xFFFFFED4,
    AUDIOLIB_ERR_HW_NOT_READY = 0xFFFFFED3,
    AUDIOLIB_ERR_HW_FAILED_TO_GET_PLAYSTATE = 0xFFFFFED2,
    AUDIOLIB_ERR_HW_FAILED_TO_PLAY_CUE = 0xFFFFFED1,
    AUDIOLIB_ERR_HW_FAILED_TO_STOP_CUE = 0xFFFFFED0,
    AUDIOLIB_ERR_HW_FAILED_TO_PAUSE_CUE = 0xFFFFFECF,
    AUDIOLIB_ERR_HW_FAILED_TO_UNPAUSE_CUE = 0xFFFFFECE,
    AUDIOLIB_ERR_HW_CALLBACK_REGISTER_FAILED = 0xFFFFFECD,
    AUDIOLIB_ERR_HW_SOUNDBANK_INVALID = 0xFFFFFECC,
    AUDIOLIB_ERR_HW_SOUNDBANK_LOAD_FAILED = 0xFFFFFECB,
    AUDIOLIB_ERR_HW_SOUNDBANK_CREATE_FAILED = 0xFFFFFECA,
    AUDIOLIB_ERR_HW_NOT_SUPPORTED = 0xFFFFFEC9,
    AUDIOLIB_ERR_HW_MISC = 0xFFFFFEC8,
    AUDIOLIB_ERR_HW_UNKNOWN_FOLEY = 0xFFFFFEC7,
    AUDIOLIB_ERR_HW_UNKNOWN_CATEGORY = 0xFFFFFEC6,
    AUDIOLIB_ERR_HW_FAILED_CATEGORY_SET = 0xFFFFFEC5,
    AUDIOLIB_ERR_HW_FAILED_VOICE_CREATE = 0xFFFFFEC4,
    AUDIOLIB_ERR_HW_FAILED_VOICES_SET = 0xFFFFFEC3,
    AUDIOLIB_ERR_HW_NUM_CHANNELS_0 = 0xFFFFFEC2,
    AUDIOLIB_ERR_HW_NUM_CHANNELS = 0xFFFFFEC1,
    AUDIOLIB_ERR_HW_VARIATION_MISMATCH = 0xFFFFFEC0,
    AUDIOLIB_ERR_STREAM_OUTOFMEMORY = 0xFFFFFE70,
    AUDIOLIB_ERR_STREAM_TIMEOUT_ERROR = 0xFFFFFE6F,
    AUDIOLIB_ERR_STREAM_MISC_ERROR = 0xFFFFFE6E,
    AUDIOLIB_ERR_TRY_CACHE_LATER = 0xFFFFFE6D,
    AUDIOLIB_ERR_NOT_IMPLEMENTED = 0xFFFFD8F0,
};

enum AUDIOLIB_REVERB_ROOM_TYPE
{
    AUDIOLIB_REVERB_ROOM_TYPE_DEFAULT = 0x0,
    AUDIOLIB_REVERB_ROOM_TYPE_GENERIC = 0x1,
    AUDIOLIB_REVERB_ROOM_TYPE_PADDEDCELL = 0x2,
    AUDIOLIB_REVERB_ROOM_TYPE_ROOM = 0x3,
    AUDIOLIB_REVERB_ROOM_TYPE_BATHROOM = 0x4,
    AUDIOLIB_REVERB_ROOM_TYPE_LIVINGROOM = 0x5,
    AUDIOLIB_REVERB_ROOM_TYPE_STONEROOM = 0x6,
    AUDIOLIB_REVERB_ROOM_TYPE_AUDITORIUM = 0x7,
    AUDIOLIB_REVERB_ROOM_TYPE_CONCERTHALL = 0x8,
    AUDIOLIB_REVERB_ROOM_TYPE_CAVE = 0x9,
    AUDIOLIB_REVERB_ROOM_TYPE_ARENA = 0xA,
    AUDIOLIB_REVERB_ROOM_TYPE_HANGAR = 0xB,
    AUDIOLIB_REVERB_ROOM_TYPE_CARPETEDHALLWAY = 0xC,
    AUDIOLIB_REVERB_ROOM_TYPE_HALLWAY = 0xD,
    AUDIOLIB_REVERB_ROOM_TYPE_STONECORRIDOR = 0xE,
    AUDIOLIB_REVERB_ROOM_TYPE_ALLEY = 0xF,
    AUDIOLIB_REVERB_ROOM_TYPE_FOREST = 0x10,
    AUDIOLIB_REVERB_ROOM_TYPE_CITY = 0x11,
    AUDIOLIB_REVERB_ROOM_TYPE_MOUNTAINS = 0x12,
    AUDIOLIB_REVERB_ROOM_TYPE_QUARRY = 0x13,
    AUDIOLIB_REVERB_ROOM_TYPE_PLAIN = 0x14,
    AUDIOLIB_REVERB_ROOM_TYPE_PARKINGLOT = 0x15,
    AUDIOLIB_REVERB_ROOM_TYPE_SEWERPIPE = 0x16,
    AUDIOLIB_REVERB_ROOM_TYPE_UNDERWATER = 0x17,
    AUDIOLIB_REVERB_ROOM_TYPE_SMALLROOM = 0x18,
    AUDIOLIB_REVERB_ROOM_TYPE_MEDIUMROOM = 0x19,
    AUDIOLIB_REVERB_ROOM_TYPE_LARGEROOM = 0x1A,
    AUDIOLIB_REVERB_ROOM_TYPE_MEDIUMHALL = 0x1B,
    AUDIOLIB_REVERB_ROOM_TYPE_LARGEHALL = 0x1C,
    AUDIOLIB_REVERB_ROOM_TYPE_PLATE = 0x1D,
    AUDIOLIB_NUM_REVERB_ROOM_TYPES = 0x1E,
};

struct AUDIOLIB_CUE_CALLBACK_DATA
{
    void(__cdecl* function)(AUDIOLIB_CUE_CALLBACK_DATA*);
    unsigned __int16 action;
    int play_id;
    void* user_data;
    int time;
    char marker_text[64];
};

struct audiolib_low_pass_info
{
    int freq;
    float effect;
};

struct audiolib_reverb_info
{
    AUDIOLIB_REVERB_ROOM_TYPE room_type;
    float effect;
};

struct audiolib_dsp_info
{
    audiolib_low_pass_info low_pass;
    audiolib_reverb_info reverb;
};

struct audiolib_params
{
    unsigned __int16 flags;
    unsigned __int16 callback_flags;
    void(__cdecl* callback_func)(AUDIOLIB_CUE_CALLBACK_DATA*);
    void* callback_data;
    char priority;
    float volume;
    float pitch;
    float pan;
    char rolloff_curve;
    float curve_midpoint;
    unsigned __int16 dsp_type;
    audiolib_dsp_info dsp;
    float distance_min;
    float distance_max;
    unsigned int delay_ms;
    unsigned int fade_ms;
    unsigned int offset_ms;
    vector pos;
    vector orient;
    vector velocity;
    __int16 num_positions;
    vector position_list[16];
};